# -*- coding: utf-8 -*-
"""DevJrBr-PythonDoInicio-Condicionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSRTHHSdhjdDTqS3nZ4HLs-bkj9nF-mc

# Python do Início - DevJrBR

## Operadores condicionais

### links úteis

- https://docs.python.org/3/tutorial/controlflow.html#if-statements
- https://docs.python.org/3/reference/compound_stmts.html#the-if-statement
- https://realpython.com/python-conditional-statements/

### if - elif - else
"""

MAIORIDADE = 18

idade = input('Qual a idade (em anos)?')

idade = int(idade)

if idade < MAIORIDADE:
  print('É menor')
else:
  print('É maior')

# vida real
MAIORIDADE = 18

idade = input('Qual a idade (em anos)?')
idade = int(idade)

if idade < 0:
  print('Espertinho, idade inválida!')
else:
  if idade < MAIORIDADE:
    print('É menor')
  else:
    print('É maior')

# vida real (mais pythonico)
MAIORIDADE = 18

idade = input('Qual a idade (em anos)?')
idade = int(idade)

if idade < 0:
  print('Espertinho, idade inválida!')
elif idade < MAIORIDADE:
  print('É menor')
else:
  print('É maior')

lista = [12, 10, 3, 4, 5, 'ok', 1.2, complex(2, 1), ['a', 'b', 'c'] ]

if 10 in lista:
  print('A lista tem um dez')
elif 12 in lista:
  print('A lista em um doze')
else:
  print('Deu caca.')

# listar
# imprimir
# excluir
# criar

operacao = input('O que posso fazer por você hoje? ')

if operacao == 'c' or operacao == 'criar':
  print('CRIEI TUDO')
  len(operacao)
elif operacao == 'i' or operacao == 'imprimir':
  print('OLHA NA IMPRESSORA, ESPERTO')
elif operacao == 'e' or operacao == 'excluir':
  print('PERDEU TUDO')
elif operacao == 'l' or operacao == 'listar':
  print('R$ 0,00')

operacao = input('O que posso fazer por você hoje? ')

if operacao in ['c', 'criar']:
  print('CRIEI TUDO')
  len(operacao)
elif operacao in ('i', 'imprimir'):
  print('OLHA NA IMPRESSORA, ESPERTO')
elif operacao in {'e', 'excluir'}:
  print('PERDEU TUDO')
elif operacao in ['l', 'listar']:
  print('R$ 0,00')

OPERACOES = {
    'c': 'CRIEI TUDO',
    'criar': 'CRIEI TUDO',
    #
    'i': 'OLHA NA IMPRESSORA, ESPERTO',
    'imprimir': 'OLHA NA IMPRESSORA, ESPERTO',
    #
    'e': 'PERDEU TUDO',
    'excluir': 'PERDEU TUDO',
    #
    'l': 'R$ 0,00',
    'listar': 'R$ 0,00',
}

operacao = input('O que posso fazer por você hoje? ')

resultado_operacao = OPERACOES[operacao]
print(resultado_operacao)

"""### operador ternário"""

operacao = input('O que posso fazer por você hoje? ')

tipo_de_comando = 'Forma compacta' if len(operacao) < 2 else 'Forma completa'
# (condicao)?(valor se verdadeiro):(valor se falso)
# (valor se verdadeiro) if (condicao) else (valor se falso)

print(tipo_de_comando)

operacao

"""### expressões de atribuição (python 3.8 ou superior)

"""

# walrus

tamanho_operação = len(operacao)
if tamanho_operação > 1:
  print('Forma completa de tamanho', tamanho_operação)
else:
  print('Forma compacta')

operacao = input('O que posso fazer por você hoje? ')

if (tamanho_operação := len(operacao)) > 1:
  print('Forma completa de tamanho', tamanho_operação)
else:
  print(tamanho_operação)
  print('Forma compacta')

"""### match (python 3.10 ou superior)"""

operacao = input('O que posso fazer por você hoje? ')

match operacao:
  case 'c' | 'criar':
    print('CRIEI TUDO')
  case 'i' | 'incluir':
    print('OLHA NA IMPRESSORA, ESPERTO')
  case 'e' | 'excluir':
    print('PERDEU TUDO')
  case 'l' | 'listar':
    print('R$ 0,00')

operacao = ['criar', 'teste.txt', 'teste2.txt', 'badanha.txt', 24 ,5 ,654 ,6 ,5]
# operacao = 'teste'
#
match operacao:
  case ['c' | 'criar', *arquivos]:
    print('CRIEI TUDO', arquivos)
    if len(arquivos) > 10:
      print('Preguiça, mano, manda menos!')
  case 'i' | 'incluir':
    print('OLHA NA IMPRESSORA, ESPERTO')
  case 'e' | 'excluir':
    print('PERDEU TUDO')
  case 'l' | 'listar':
    print('R$ 0,00')
  case _:
    print('Nem te conheço')
